### PR TITLE
Gorli tv launch release 0.1

### PR DESCRIPTION
**Pull request by criticaltv**

### CODE REVIEW

**Comment by criticaltv** [comment]
This is first release of Görli TV.

We hope you enjoy :)

Screenshot from 2020-02-22 03-07-13

**Review by q9f — APPROVED** [review]

**Comment by criticaltv** [comment]
Who can merge this?

**Comment by criticaltv** [comment]
Hi @q9f are you able to merge these changes also?

**Comment by q9f** [comment]
Hi, there is no consensus to host this project in the Görli organization. Sorry.

**Pull request closed without merging**
